### ISSUE TITLE
WHMCS UNIQUE EMAIL

### ISSUE THREAD

**Issue by GameTrackerPW** [Rynoxx/sentora-whmcs#6]
Hey i have now installed Sentora and is working ok but i become every time i start module create on WHMCS this error:

Account couldn't be created, couldn't verify that email 'xxxxxxxxxxxx@gmail.com' is unique

And debug is this:

Caught exception: Unable to parse response body into XML: String could not be parsed as XML

#0 /home/boostbal/webcloud.pro/modules/servers/sentora/lib/senitor/src/Handlers/XmwsResponse.php(57): GuzzleHttp\Message\Response->xml()
#1 /home/boostbal/webcloud.pro/modules/servers/sentora/lib/senitor/src/Handlers/XmwsResponse.php(35): Ballen\Senitor\Handlers\XmwsResponse->checkErrors()
#2 /home/boostbal/webcloud.pro/modules/servers/sentora/lib/senitor/src/Handlers/XmwsRequest.php(92): Ballen\Senitor\Handlers\XmwsResponse->__construct(Object(GuzzleHttp\Message\Response))
#3 /home/boostbal/webcloud.pro/modules/servers/sentora/lib/senitor/src/Senitor.php(130): Ballen\Senitor\Handlers\XmwsRequest->send()
#4 /home/boostbal/webcloud.pro/modules/servers/sentora/sentora.php(348): Ballen\Senitor\Senitor->send()
#5 /home/boostbal/webcloud.pro/modules/servers/sentora/sentora.php(412): sendSenitorRequest(Array, 'whmcs', 'CheckUserEmailI...', Array)
#6 /home/boostbal/webcloud.pro/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): sentora_CreateAccount(Array)
#7 /home/boostbal/webcloud.pro/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call()
#8 /home/boostbal/webcloud.pro/includes/modulefunctions.php(0): WHMCS\Module\Server->call()
#9 /home/boostbal/webcloud.pro/includes/modulefunctions.php(0): ModuleCallFunction()
#10 /home/boostbal/webcloud.pro/includes/orderfunctions.php(0): ServerCreateAccount()
#11 /home/boostbal/webcloud.pro/admin/orders.php(0): acceptOrder()
#12 {main}
Debug string from Senitor:

**Comment by Rynoxx** [comment]
Which PHP version and Sentora version are you running? And what is your error reporting in PHP set to?

**Comment by GameTrackerPW** [comment]
Php version is 5.3.3 and Sentora is 1.0.3

**Comment by Rynoxx** [comment]
Update your PHP version to 5.6 and the error should be gone. This module doesn't support anything below PHP 5.6, [as they are no longer supported by PHP](http://php.net/supported-versions.php)

**Comment by GameTrackerPW** [comment]
Oh ok i will try and say here is ok or no

**Comment by GameTrackerPW** [comment]
Hmm now i have updated version to 5.6 and now when i go to site is downloading me file Download every time i refresh site is down and download me file with name Download

**Comment by JustSentora** [comment]
http://project-veronica.info/

**Comment by Rynoxx** [comment]
Double check that mod-php for your apache is for php 5.6 as well

**Comment by GameTrackerPW** [comment]
How can i check theat i have check is mod-php working and it says Syntax OK

**Comment by Rynoxx** [comment]
If you're running ubuntu/debian or a derivative thereof, you can run `apache2ctl -M` if you're running CentOS/Fedora `httpd -M` should work.

The output should include something like `phpX_module`

**Comment by GameTrackerPW** [comment]
I have now see i have PHP error when i type php -v i become this error:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/suhosin.so' - /usr/lib64/php/modules/suhosin.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by Rynoxx** [comment]
http://forums.sentora.org/showthread.php?tid=780&pid=5447#pid5447

**Comment by GameTrackerPW** [comment]
Ok i will try it
